### ISSUE TITLE
Remove bundling

### ISSUE THREAD

**Issue by ai** [komlev/tiny-use-media#1]
You do not need `vite` to publish JS to `npm`.

It is even better to put a separated ESM files rather than big JS bundle. Anyway, end-user will use own bundler. Since we have 2 different bundles (first one is your Vite, second is end-user webpack) they could conflict and increase file size and add unnecessary polyfills.

**Comment by komlev** [comment]
Good advice, I'll make those changes later this week

**Comment by komlev** [comment]
@ai done in this PR https://github.com/komlev/tiny-use-media/pull/2
